{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "scavenger-fox.fullname" . }}
  labels:
    {{- include "scavenger-fox.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "scavenger-fox.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- range .Values.networkPolicy.ingressCIDRs }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
  egress:
    {{- if .Values.postgresql.enabled }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "scavenger-fox.name" . }}-postgresql
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: {{ .Values.postgresql.service.port }}
    {{- else }}
    {{- if .Values.networkPolicy.egress.postgres.enabled }}
    - to:
        {{- range .Values.networkPolicy.egress.postgres.cidrs }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.egress.postgres.port }}
    {{- end }}
    {{- end }}
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
