{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scavenger-fox.postgresql.secretName" . }}
  labels:
    {{- include "scavenger-fox.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "scavenger-fox.postgresql.databaseUrl" . | quote }}
{{- end }}
