apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scavenger-fox
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/gwaland/BS-scavenger-fox.git'
    targetRevision: main
    path: chart
    helm:
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: scavenger-fox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
